linux update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,17 +2,17 @@
 
 echo "Checking if Python exists"
 # Check for Python 3 and assign its path to a variable
-if command -v python3 > /dev/null 2>&1; then
-    py=$(which python3)
-    echo "Using python3"
+if command -v python3 >/dev/null 2>&1; then
+  py=$(which python3)
+  echo "Using python3"
 else
-    if python --version 2>&1 | grep -q '3.'; then
-        py=$(which python)
-        echo "Using python"
-    else
-        echo "Please install Python3 or 3.11 manually."
-        exit 1
-    fi
+  if python --version 2>&1 | grep -q '3.'; then
+    py=$(which python)
+    echo "Using python"
+  else
+    echo "Please install Python3 or 3.11 manually."
+    exit 1
+  fi
 fi
 
 echo "Installing required components"
@@ -22,15 +22,15 @@ $py -m venv venv
 # Dynamically get the current directory's virtual environment activation script
 VENV_DIR="$PWD/venv"
 if [ -d "$VENV_DIR" ]; then
-    echo "Activating virtual environment in $VENV_DIR"
-    source "$VENV_DIR/bin/activate"
+  echo "Activating virtual environment in $VENV_DIR"
+  source "$VENV_DIR/bin/activate"
 else
-    echo "Virtual environment not found in $VENV_DIR"
-    exit 1
+  echo "Virtual environment not found in $VENV_DIR"
+  exit 1
 fi
 
 # Install required Python packages
-"$VENV_DIR/bin/pip" install --upgrade streamlink aiohttp aiofiles orjson uvloop
+"$VENV_DIR/bin/pip" install --upgrade streamlink aiohttp aiofiles orjson uvloop dotenv
 
 # Deactivate the virtual environment
 deactivate
